<<<<<<< HEAD
spring.application.name=SpringSecurityMySqlAuthdDemo
=======
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/jwt_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


>>>>>>> 8c745f828a98b362c4932c0ae1885e75293fbe40
